### ISSUE TITLE
tcpcopy日志中报错[warn] no first auth:xxxxx

### ISSUE THREAD

**Issue by blackghost-01** [session-replay-tools/mysql-replay-module#5]
Hi，请教一下，回放mysql流量时，online mysql server短的tcpcopy日志一直报如下warning:
2016/08/10 18:23:26 +796 [warn] no first auth:43681
2016/08/10 18:23:26 +915 [warn] no first auth:43800
2016/08/10 18:23:27 +016 [warn] no first auth:43884
2016/08/10 18:23:27 +017 [warn] no first auth:43884
2016/08/10 18:23:27 +070 [warn] no first auth:43947
2016/08/10 18:23:27 +277 [warn] no first auth:44147
2016/08/10 18:23:27 +279 [warn] no first auth:44147
2016/08/10 18:23:27 +293 [warn] no first auth:44164
2016/08/10 18:23:27 +322 [warn] no first auth:44212
2016/08/10 18:23:27 +323 [warn] no first auth:44212
2016/08/10 18:23:27 +569 [warn] no first auth:44507
2016/08/10 18:23:27 +634 [warn] no first auth:44587
2016/08/10 18:23:27 +714 [warn] no first auth:44675
2016/08/10 18:23:27 +737 [warn] no first auth:44694
2016/08/10 18:23:27 +738 [warn] no first auth:44694
2016/08/10 18:23:27 +899 [warn] no first auth:44823

test server上无mysql请求，请问是什么问题呢？

tcpcopy version:1.0.0
intercept version:1.0.0
OS : CentOS release 6.5 (Final)  2.6.32-431.el6.x86_64
编译参数:
tcpcopy : ./configure --set-protocol-module=mysql-replay-module --with-debug
intercept : ./configure --with-resp-payload

**Comment by wangbin579** [comment]
不好意思，这么久才回复（github没有给我发邮件提醒，目前只有tcpcopy项目那个才发邮件）

回放MySQL流量比较麻烦，session半路回放的时候，tcpcopy会去找有没有之前的登入校验信息（比如第一次认证first auth信息），如果找到，就能顺利回放，否则不能回放，于是就报上面类似的信息。

可以采用如下方法来解决此问题：
方法1：
用模块 https://github.com/session-replay-tools/mysql-sgt-replay-module，避开复杂的认证过程，只要捕获到一次完整的MySQL session交互过程，即可。

方法2：
等待，直到线上有完整的MySQL session交互，就会开始有流量，之后随着完整的session越来越多，流量就会逐步多起来。
btw，目前我这边就是这样回放的

方法3：
重启线上业务，让连接重新建立起来，这种一般不推荐

**Comment by blackghost-01** [comment]
谢谢，暂时没有用这个方案测试了，持续关注中

**Comment by chenmin1992** [comment]
@blackghost-01 您好，请问您之后用什么方法测试了？可以分享一下吗？

**Comment by gongna-au** [comment]
> 谢谢，暂时没有用这个方案测试了，持续关注中
您好，请问您之后用什么方法测试了？可以分享一下吗？
