### ISSUE TITLE
prepare语句的copy问题

### ISSUE THREAD

**Issue by lysu** [session-replay-tools/mysql-replay-module#6]
最近尝试使用tcpcopy引流线上流量~感觉挺好用，但发现个问题就是关于mysql的prepare。。

经过了解mysql整个prepare过程会先发起 1. prepare命令并接受成功返回的statementid，2.再发起execute命令并带上前面返回的statementid 进行执行。。。

我们现在打算引流正常的线上流量到一个线下测试版本的mysql代理工具(主要想测试下改动功能，和mysql兼容性之类 嘿嘿)…问题就出现了

用户发起prepare请求后正常流量正常执行并返回线上机器产生的statementid， 但对于copy出来的流量到我们线下mysql后长生的statementid需要被抛弃；之后用户端会用线上的statementid再次请求，然后线上可以正常执行，但copy出来的流量中带的是线上的statementid，线下无法的mysql一定是找不到这个id的就会报错- -~

简单总结就是：用户再次发起execute带的stmtid被copy后是线上的而不是copy流量返回的= =

不造大大之前有没有遇到过类似情况哈~有没有啥建议肿么解决。。。(拍脑袋想感觉如果在mysql module再搞个stmtid的映射之类的- - 不过初接tcpcopy不知道能否实现)

非常感谢~

**Comment by wangbin579** [comment]
非常抱歉，现在才看到这个issue。
首先请问stmt id为什么变化了（据之前的sysbench测试，stmt id在两端是一样的，因此没有考虑到stmt id不一样导致的问题）；其次，要改变stmt id，最好在MySQL的代理端去做修改，这样省事，当然tcpcopy replay模块也能实现，就是麻烦一些；最后，希望能够得到你的答复，在此先多谢了

**Comment by lysu** [comment]
抱歉也才看到回复，晚上研究了下基本知道问题了~

补充下背景 我们的测试场景是copy到新老两个MySQL 的代理，代理再去访问mysql，我们的代理会自己生成stmtid并和实际多个mysql后端的stmtid做映射关联，而问题就是出现在我们的代理生成的stmtid生成规则上- - 

多谢提醒，研究了下正常情况stmt id对于mysql应该是一样的...

正常对mysql应该是这样， copy机器同时建立两个连接到两个mysql，mysql每收到连接后会new一个THD，之后stmt-id生成就在这个THD上的变量statement_id_counter来生成stmt-id，https://github.com/mysql/mysql-server/blob/5.7/sql/sql_prepare.cc#L3019，因为两边都一样各自随着请求从1，2，3...开始递增，所以应该都一样

而导致不一样是因为我们自己的mysql代理在stmtid生成规则上和mysql有出入。。我们proxy用的是单线eventloop线程那种模式，然后类似statement_id_counter的东西被挂到eventloop线程上这样虽然可以保证递增不重复- -，但就不像mysql那样A连接线程内递增，我们那个生成的全局递增- - 然后两端就不一样了 囧

想了下我们只要把proxy改下，把这个statement_id_counter搞到类似的session维度应该和mysql一样了。。这个算tcp-copy发现了我们proxy的bug哈 感谢~
