### ISSUE TITLE
MySQL复制时，有时候会丢失数字值

### ISSUE THREAD

**Issue by chenmin1992** [session-replay-tools/mysql-replay-module#7]
比如
UPDATE b_order_share SET order_status=1 WHERE oid =(7889924) AND xdy_id = xxx
SELECT count,xid FROM b_free_order_log WHERE xid =(xxx) AND grab_time >=2018-09-11
等号之后的数字会丢失
手动执行时数据库日志不会报错
而原数据库是完整可以正常执行的SQL.

**Comment by chenmin1992** [comment]
2018/09/11 11:33:29.640 session.go:818: [warning] con:19315 parse error:
line 1 column 64 near " ) " (total length 67)
SELECT `zone_id`,`zone_name` FROM `zone` WHERE ( `zone_id` IN () ) 
"SELECT `zone_id`,`zone_name` FROM `zone` WHERE ( `zone_id` IN () ) "
line 1 column 64 near " ) " (total length 67)

**Comment by wangbin579** [comment]
那只能抓包分析了

**Comment by wangbin579** [comment]
tcpcopy除了修改认证信息，不会去修改应用层sql数据。
最好通过抓包分析来看看转发的sql是否变化了
