### ISSUE TITLE
tcpcopy日志中报[warn] user:,pwd is null

### ISSUE THREAD

**Issue by bxhbpdxhzGithub** [session-replay-tools/mysql-replay-module#8]
2020/11/30 16:26:39 +619 [warn] user:,pwd is null
2020/11/30 16:26:39 +619 [warn] change fir auth unsuccessful
2020/11/30 16:26:39 +619 [info] we can not continue:60084

tcpcopy/conf/plugin.conf中的账号密码也配了
请问这个是什么地方没有配正确？

**Comment by wangbin579** [comment]
那只能抓包分析了，抓包获取的信息用户名也是空，密码也是空
